# Generated by Django 5.0 on 2023-12-05 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='productosImplementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImplementoDeportivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tamaños',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='prenda')),
                ('descripcion', models.TextField(max_length=540)),
                ('precio', models.FloatField()),
                ('talla', models.CharField(max_length=4)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
        migrations.CreateModel(
            name='ImplementosDeportivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=40)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Deportivo')),
                ('descripcion', models.TextField(max_length=540)),
                ('precio', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productosimplementos')),
                ('tamaños', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tamaños')),
            ],
        ),
    ]
